### ISSUE TITLE
Cannot to the server

### ISSUE THREAD

**Issue by pascaldugousset** [ThanosSiopoudis/BarrelApp#63]
Hello i've the same problem that you have resolved some time ago (i'm french user)
trying to create an empty barrel or a barrel from an .exe i've the error message about 'cannot connect to the server'
please could you check the permission on the server files ?
thanks

**Comment by ThanosSiopoudis** [comment]
Hi,
the barrel app is undergoing a major overhaul for the 2.0 version, and the server api has also been completely changed, which is why the 0.9 version doesn't work anymore.

You can download the source code and compile the 2.0 version if you'd like, which has great new features (like Wine64 support and portable bundles) but it is still quite buggy.

**Comment by pascaldugousset** [comment]
Tanks for the answer
But how download ans compile thé new version please ?

Envoyé de mon iPhone

**Comment by ThanosSiopoudis** [comment]
You need to checkout with git (with submodules) and then open the project in Xcode and compile from there. Sorry there isn't a more detailed guide, but you can find plenty on the internet.
Thanks

**Comment by pascaldugousset** [comment]
Thanks 

I m using Barrel and Wine under Yosemite to create Mac version of Windows games like Warcraft

Is the new version of Barrel working in El Capitan ? The 0.9 didn't work 
And the wine version of games didn't work too in fact (create with winery, problème with X11)

Envoyé de mon iPhone

**Comment by ThanosSiopoudis** [comment]
Yes, the 2.0 version is compatible with 10.9, 10.10 and 10.11
While it is in no way complete yet, you can in fact go through the whole import process and create a new functioning Barrel

**Comment by pascaldugousset** [comment]
hello i've tried to compile with Xcode under yosemite
but i've a problem with the projecti've this error
The selected team's agent, 'Pascal Dugousset' must agree to the latest Program License Agreement.  Please visit the Member Center.https://developer.apple.com/membercenter
i've visit the site and agree the program, as i'm registered developer since julybut the problem persist
so how resolved it please ?
Date: Sat, 15 Aug 2015 04:52:09 -0700
