### ISSUE TITLE
Is the app still active?

### ISSUE THREAD

**Issue by aayushkapoor206** [ThanosSiopoudis/BarrelApp#64]

**Comment by ThanosSiopoudis** [comment]
Yes, I haven't committed code in a while, but version 2.0 only needs a few more tweaks and it will be ready eventually. Compiling from the source works for creating a new bundle.

**Comment by aayushkapoor206** [comment]
Excellent! I have really high appreciation for your project. There's no other Wine + GUI for OS X that's actually good!

I wanted to start something similar but currently lack the expertise to do so.

Good luck!
